name: Performance

on:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install gradle profiler
      run: sdk install gradleprofiler
