name: Performance

on:
  workflow_dispatch:
    
jobs:
  performance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install sdkman
      run: |
        curl -s https://get.sdkman.io | bash

    - name: install gradle profiler
      run: |
        source ~/.sdkman/bin/sdkman-init.sh
        sdk install gradleprofiler
